"use strict";
exports.__esModule = true;
exports.CollectEnum = exports.AirSupplyEnum = exports.DropChanceEnum = exports.EnemiesEnum = exports.GameLocationEnum = exports.ItemRarityEnum = exports.WeaponEnum = exports.ItemTypeEnum = void 0;
var ItemTypeEnum;
(function (ItemTypeEnum) {
    ItemTypeEnum["weapon"] = "Weapon";
    ItemTypeEnum["armor"] = "Armor";
    ItemTypeEnum["consumables"] = "Consumables";
    ItemTypeEnum["special"] = "Special";
    ItemTypeEnum["ingredients"] = "Ingredients";
})(ItemTypeEnum = exports.ItemTypeEnum || (exports.ItemTypeEnum = {}));
var WeaponEnum;
(function (WeaponEnum) {
    WeaponEnum["axe"] = "Axe";
    WeaponEnum["dagger"] = "Dagger";
    WeaponEnum["twoHandedSword"] = "Two-Handed Sword";
    WeaponEnum["dualSwords"] = "Dual swords";
    WeaponEnum["glove"] = "Glove";
    WeaponEnum["tonfa"] = "Tonfa";
    WeaponEnum["bat"] = "Bat";
    WeaponEnum["whip"] = "Whip";
    WeaponEnum["throw"] = "Throw";
    WeaponEnum["shuriken"] = "Shuriken";
    WeaponEnum["bow"] = "Bow";
    WeaponEnum["crossbow"] = "Crossbow";
    WeaponEnum["pistol"] = "Pistol";
    WeaponEnum["assaultRifle"] = "Assault Rifle";
    WeaponEnum["sniperRifle"] = "Sniper Rifle";
    WeaponEnum["hammer"] = "Hammer";
    WeaponEnum["spear"] = "Spear";
    WeaponEnum["nunchaku"] = "Nunchaku";
    WeaponEnum["rapier"] = "Rapier";
    WeaponEnum["guitar"] = "Guitar";
})(WeaponEnum = exports.WeaponEnum || (exports.WeaponEnum = {}));
var ItemRarityEnum;
(function (ItemRarityEnum) {
    ItemRarityEnum["base"] = "base";
    ItemRarityEnum["green"] = "green";
    ItemRarityEnum["blue"] = "blue";
    ItemRarityEnum["purple"] = "purple";
    ItemRarityEnum["yellow"] = "yellow";
})(ItemRarityEnum = exports.ItemRarityEnum || (exports.ItemRarityEnum = {}));
var GameLocationEnum;
(function (GameLocationEnum) {
    GameLocationEnum["alley"] = "Alley";
    GameLocationEnum["archeryRange"] = "Archery Range";
    GameLocationEnum["school"] = "School";
    GameLocationEnum["avenue"] = "Avenue";
    GameLocationEnum["temple"] = "Temple";
    GameLocationEnum["pond"] = "Pond";
    GameLocationEnum["hospital"] = "Hospital";
    GameLocationEnum["cemetery"] = "Cemetery";
    GameLocationEnum["factory"] = "Factory";
    GameLocationEnum["chapel"] = "Chapel";
    GameLocationEnum["dock"] = "Dock";
    GameLocationEnum["uptown"] = "Uptown";
    GameLocationEnum["forest"] = "Forest";
    GameLocationEnum["beach"] = "Beach";
    GameLocationEnum["hotel"] = "Hotel";
    GameLocationEnum["researchCenter"] = "Research Center";
})(GameLocationEnum = exports.GameLocationEnum || (exports.GameLocationEnum = {}));
var EnemiesEnum;
(function (EnemiesEnum) {
    EnemiesEnum["chicken"] = "chicken";
    EnemiesEnum["bat"] = "bat";
    EnemiesEnum["wildBoar"] = "wild boar";
    EnemiesEnum["wildDog"] = "wild dog";
    EnemiesEnum["wolf"] = "wolf";
    EnemiesEnum["bear"] = "bear";
    EnemiesEnum["drWickeline"] = "dr. Wickeline";
})(EnemiesEnum = exports.EnemiesEnum || (exports.EnemiesEnum = {}));
var DropChanceEnum;
(function (DropChanceEnum) {
    DropChanceEnum["always"] = "always";
    DropChanceEnum["rarely"] = "rarely";
    DropChanceEnum["often"] = "often";
})(DropChanceEnum = exports.DropChanceEnum || (exports.DropChanceEnum = {}));
var AirSupplyEnum;
(function (AirSupplyEnum) {
    AirSupplyEnum["green"] = "green";
    AirSupplyEnum["blue"] = "blue";
    AirSupplyEnum["purple"] = "purple";
    AirSupplyEnum["yellow"] = "yellow";
})(AirSupplyEnum = exports.AirSupplyEnum || (exports.AirSupplyEnum = {}));
var CollectEnum;
(function (CollectEnum) {
    CollectEnum["freshWaterFishing"] = "Fresh water fishing";
    CollectEnum["seaWaterFishing"] = "Sea water fishing";
    CollectEnum["potatoVine"] = "Potato vine";
    CollectEnum["pileOfStones"] = "Pile of stones";
    CollectEnum["woodpile"] = "Woodpile";
    CollectEnum["treeOfLife"] = "Ancient Tree";
})(CollectEnum = exports.CollectEnum || (exports.CollectEnum = {}));
